# apiVersion: v1
# kind: Ingress
# metadata:
  # name: simple-ingress
  # namespace: default
  # annotations:
    # kubernetes.io/ingress.class: "tectonic"
    # ingress.kubernetes.io/rewrite-target: /
    # ingress.kubernetes.io/ssl-redirect: "true"
    # ingress.kubernetes.io/use-port-in-redirects: "true"
# spec:
  # rules:
    # - host: tectonic.seatwave.com
      # http:
        # paths:
          # - path: /simple-deployment
            # backend:
              # serviceName: simple-service
              # servicePort: 81
